# language.py

DETAILED_CATEGORIES = {
    'EN': {
        "Web Browsers": "app", "Compression": "app", "Developer Tools": "app",
        "Messaging": "app", "Imaging": "app", "Media": "app", "Security": "app",
        "Utilities": "app", "VC++ Redistributables": "app", ".NET": "app",
        "Games": "game"
    },
    'VN': {
        "Trình duyệt Web": "app", "Nén & Giải nén": "app", "Công cụ Lập trình": "app",
        "Nhắn tin": "app", "Xử lý Ảnh": "app", "Nghe nhạc & Xem phim": "app", "Bảo mật": "app",
        "Tiện ích": "app", "VC++ Redistributables": "app", ".NET": "app",
        "Trò chơi": "game"
    }
}

TRANSLATIONS = {
    'EN': {
        'window_title': "Application Installer", 'tab_all': "All", 'tab_apps': "Apps", 'tab_games': "Games",
        'search_label': "Search:", 'search_placeholder': "Enter name...", 'install_from_label': "Install from:",
        'install_from_combo_current': "Current Tab", 'install_from_combo_all': "All", 'install_from_combo_apps': "Apps",
        'install_from_combo_games': "Games", 'export_btn': "Export", 'import_btn': "Import", 'install_btn': "Install",
        'tray_tooltip': "Application Installer", 'tray_main_screen': "Main screen", 'tray_escape': "Escape",
        'tray_running_title': "Running in background", 'tray_running_msg': "Application is still running. Click the tray icon to reopen.",
        'settings_title': "Settings", 'theme_label': "Theme:", 'language_label': "Language:",
        'show_progress_check': "Show installation progress dialog", 'auto_select_check': "Auto-select item upon creation",
        'auto_minimize_tray_check': "Automatically minimize to system tray", 'add_item_title': "Add New Item",
        'item_name_label': "Item Name:", 'item_name_placeholder': "e.g., Google Chrome", 'item_type_label': "Item Type:",
        'item_type_app': "Application", 'item_type_game': "Game", 'msg_no_selection_title': "No Selection",
        'msg_no_selection_body': "Please select items to install/remove.", 'msg_confirm_delete_title': "Confirm Deletion",
        'msg_confirm_delete_body': "Are you sure you want to remove {count} selected item(s)?",
        'msg_install_complete_title': "Installation Complete", 'msg_install_complete_body': "Successfully processed {count} application(s).",
        'msg_error_title': "Error", 'msg_error_body': "An error occurred with {name}.\nError: {error}",
        'silent_args_label': "Silent Install Arguments:", 'silent_args_placeholder': "e.g., /quiet /norestart",
        'package_title': "Select Package File", 'package_placeholder': "Path to installer file (.exe, .msi, .bat)...",
        'package_label': "Select the installer package:", 'package_browse_btn': "Browse...", 'link_title': "Enter Download Link",
        'link_placeholder': "https://example.com/installer.exe", 'link_label': "Enter the direct download link:",
        'msg_invalid_link_title': "Invalid Link", 'msg_invalid_link_body': "The provided URL is not valid.",
        'silent_args_select_btn': "Select...", 'silent_args_dialog_title': "Select Silent Arguments",
        'arg_quiet': 'Quiet mode (very few prompts)', 'arg_passive': 'Passive mode (progress bar only, no interaction)',
        'arg_qn': 'Quiet with no UI (for MSI packages)', 'arg_S_case': 'Silent install (case-sensitive, for NSIS)',
        'arg_verysilent': 'Very silent (for Inno Setup)', 'arg_norestart': 'Do not restart after installation',
        'select_all_btn': "Select All",
        'deselect_all_btn': "Deselect All",
        'show_system_notifications_check': "Show all system notifications (tray icon)",
        'detailed_categories_check': "Use detailed categories for applications",
        'item_category_label': "Item Category:",
    },
    'VN': {
        'window_title': "Trình Cài Đặt Ứng Dụng",
        'tab_all': "Tất Cả",
        'tab_apps': "Ứng Dụng",
        'tab_games': "Trò Chơi",
        'search_label': "Tìm kiếm:",
        'search_placeholder': "Nhập tên để tìm...",
        'install_from_label': "Phạm vi cài đặt:",
        'install_from_combo_current': "Tab hiện tại",
        'install_from_combo_all': "Tất cả các tab",
        'install_from_combo_apps': "Chỉ ứng dụng",
        'install_from_combo_games': "Chỉ trò chơi",
        'export_btn': "Xuất...",
        'import_btn': "Nhập...",
        'install_btn': "Cài Đặt",
        'tray_tooltip': "Trình Cài Đặt Ứng Dụng",
        'tray_main_screen': "Hiển thị cửa sổ chính",
        'tray_escape': "Thoát",
        'tray_running_title': "Đang chạy nền",
        'tray_running_msg': "Ứng dụng vẫn đang chạy. Nhấn vào biểu tượng để mở lại.",
        'settings_title': "Cài Đặt",
        'theme_label': "Giao diện:",
        'language_label': "Ngôn ngữ:",
        'show_progress_check': "Hiển thị hộp thoại tiến trình cài đặt",
        'auto_select_check': "Tự động chọn mục vừa tạo",
        'auto_minimize_tray_check': "Thu về khay hệ thống khi đóng",
        'add_item_title': "Thêm Mục Mới",
        'item_name_label': "Tên mục:",
        'item_name_placeholder': "Ví dụ: Google Chrome",
        'item_type_label': "Loại mục:",
        'item_type_app': "Ứng dụng",
        'item_type_game': "Trò chơi",
        'silent_args_label': "Tham số cài đặt ẩn:",
        'silent_args_placeholder': "Ví dụ: /quiet /norestart",
        'package_title': "Chọn Tệp Cài Đặt",
        'package_placeholder': "Đường dẫn đến tệp (.exe, .msi, .bat)...",
        'package_label': "Chọn gói cài đặt từ máy tính:",
        'package_browse_btn': "Duyệt...",
        'link_title': "Nhập Liên Kết Tải Xuống",
        'link_placeholder': "https://example.com/installer.exe",
        'link_label': "Nhập liên kết tải xuống trực tiếp:",
        'silent_args_select_btn': "Chọn...",
        'silent_args_dialog_title': "Tùy chọn Cài đặt ẩn",
        'arg_quiet': 'Chế độ yên lặng (ít thông báo nhất)',
        'arg_passive': 'Chế độ thụ động (chỉ hiện tiến trình, không cần tương tác)',
        'arg_qn': 'Không giao diện (dành cho gói .msi)',
        'arg_S_case': 'Cài đặt ẩn (phân biệt HOA/thường, cho NSIS)',
        'arg_verysilent': 'Cài đặt rất ẩn (dành cho Inno Setup)',
        'arg_norestart': 'Không khởi động lại sau khi cài đặt',
        'msg_no_selection_title': "Chưa chọn mục",
        'msg_no_selection_body': "Vui lòng chọn ít nhất một mục để thực hiện.",
        'msg_confirm_delete_title': "Xác nhận Xóa",
        'msg_confirm_delete_body': "Bạn có chắc chắn muốn xóa {count} mục đã chọn?",
        'msg_install_complete_title': "Cài đặt Hoàn tất",
        'msg_install_complete_body': "Đã xử lý thành công {count} mục.",
        'msg_error_title': "Đã xảy ra lỗi",
        'msg_error_body': "Có lỗi xảy ra với mục '{name}'.\nChi tiết: {error}",
        'msg_invalid_link_title': "Liên kết không hợp lệ",
        'msg_invalid_link_body': "URL bạn cung cấp không hợp lệ hoặc không thể truy cập.",
        'select_all_btn': "Chọn Tất Cả",
        'deselect_all_btn': "Bỏ Chọn Tất Cả",
        'show_system_notifications_check': "Hiển thị tất cả thông báo hệ thống (khay)",
        'detailed_categories_check': "Sử dụng danh mục chi tiết cho ứng dụng",
        'item_category_label': "Danh mục:",
    }
}