var Languages = {
  EN: {
    // === STATUS & PROGRESS ===
    downloading: "Downloading ",
    installing: "Installing",
    uninstalling: "Uninstalling ",
    processing_wait: "Processing, please wait...",
    processing: "Processing",
    completed: "Completed",
    error_status: "Error",
    scanning_status: "Scanning...",
    scanning_updates: "Scanning for updates...",
    software_up_to_date: "Software is up to date",
    no_updates_found: "No updates were found.",
    unknown_error: "Unknown error",
    unknown: "Unknown",
    deleting: "Deleting...",
    cleanup_status: "Cleaning up system leftovers...",
    deleted: "Deleted",
    loading_text: "Scanning installed applications...",
    recovering_progress: "Scanning and recovering... {0}%",
    destroying_wait: "Destroying data. Please do not turn off the computer...",
    canceling: "Canceling...",
    clean_analyzing: "Analyzing and cleaning...",

    // === GENERAL UI & MENU ===
    window_title: "Nex-Launcher - Advanced Utility Tool",
    installer_btn: "Installer",
    uninstaller_btn: "Uninstaller",
    about_btn: "About",
    update_btn: "Check for Updates",
    menu_settings: "Settings",
    maximize_btn: "Maximize",
    restore_btn: "Restore",
    utilities_btn: "Utilities",
    tab_rec: "Recommended",
    tab_apps: "Apps",
    tab_games: "Games",
    tab_updates: "Updates",
    search_placeholder: "Search software...",
    install_btn: "Install",
    add_btn: "Add",
    delete_btn: "Delete",
    select_all: "Select All",
    deselect_all: "Deselect All",
    menu_refresh: "Refresh list",
    header_category: "Category",
    header_source: "Source",
    header_publisher: "Publisher",
    header_date: "Install Date",
    header_size: "Size",
    refresh_btn: "Refresh",
    uninstall_btn: "Uninstall",
    next_btn: "Next",
    close_btn: "Close",
    cancel_btn: "Cancel",
    save_btn: "Save",
    reset_btn: "Reset",
    edit_btn: "Edit",
    confirm_btn: "Confirm",
    tray_show: "Show",
    tray_installer: "Installer",
    tray_uninstaller: "Uninstaller",
    tray_quit: "Quit",
    copied: "Copied!",
    estimated: "Estimated",
    theme_light: "Light",
    theme_dark: "Dark",
    theme_midnight_blue: "Midnight Blue",
    theme_system: "System",
    lang_en: "English",
    lang_vi: "Tiếng Việt",
    date_format: "MM/DD/YYYY",

    // === INSTALLER ===
    no_software_selected: "No software selected",
    confirm_install_apps: "Are you sure you want to install {0} selected software?",
    start_installing: "Starting installation for ",
    apps_suffix: " apps...",
    apps_suffix_short: " apps",
    finish_installing: "Finished installing ",
    slow_down: "Please slow down!",
    refreshing_list: "Refreshing list...",
    list_refreshed: "List refreshed",
    no_changes: "No new changes detected.",
    enter_name_keyword: "Please enter Name or Keyword to search",
    searching_winget: "Searching on Winget...",
    found_results: "Found {0} results. Please copy an ID and paste it below:\n\n",
    no_results_winget: "No results found",
    no_results: "No software found",
    no_results_desc: "Try a different search term",
    add_app_title: "Add New App",
    add_app_name: "App Name",
    add_app_name_ph: "Ex: Zalo",
    add_app_category: "Category",
    add_app_category_ph: "Type or select...",
    cat_web_browsers: "Web Browsers",
    cat_dev_tools: "Developer Tools",
    cat_media: "Media",
    cat_games: "Games",
    cat_utilities: "Utilities",
    cat_messaging: "Messaging",
    cat_compression: "Compression",
    add_app_source: "Source type",
    add_app_id_ph: "Enter ID / Link / Search keyword",
    add_app_search_title: "Search on Winget",
    add_app_silent_args_ph: "Ex: /S /v/qn (Leave blank if not needed)",
    add_app_store_id_ph: "Enter Store ID",
    add_app_cancel: "Cancel",
    add_app_add: "Add",
    search_winget_title_prefix: "Search Winget: ",
    downloading_prefix: "Downloading (",
    edit_software_title: "Edit Software",
    add_software_title: "Add new software",

    // === UNINSTALLER ===
    confirm_uninstall: "Show confirmation dialog before uninstalling",
    minimize_tray_uninst_label: "Minimize to tray on uninstall",
    start_uninstalling: "Starting uninstallation for ",
    finish_uninstalling: "Finished uninstalling ",
    confirm_remove_apps: "Remove {0} apps?",
    successfully_removed: "Successfully removed",
    error_removing: "Error removing",
    no_apps: "No applications found",
    status_selected: "Selected {0} app(s)",
    delete_leftovers: "Delete Leftovers",
    no_registry_leftovers: "No registry leftovers found.",
    no_file_leftovers: "No file/folder leftovers found.",
    registry_entries: "Registry entries",
    orphan_files: "Orphan files",

    // === UTILITIES ===
    enter_destroy_path: "Enter the drive path to destroy (E.g.: \\\\.\\PhysicalDrive1 or D:)\\nWARNING: Destroying a drive will permanently erase all data!",
    destroy_anyway: "Destroy Anyway (Pass {0}/3)",
    destroy_complete: "Data destruction complete!",
    destroy_error: "Destruction error: ",
    general_error: "An error occurred: ",
    recovering_title: "Nex Launcher - Recovering: {0}%",
    enter_scan_drive: "Please enter the drive to scan (E.g.: C:, D:)",
    choose_recover_folder: "Please choose a folder to save recovered files",
    starting_scan: "Starting scan...",
    scanning_recovering: "Scanning and recovering... {0}%",
    start_recover_title: "Nex Launcher - Starting recovery...",
    recovery_complete: "Data recovery complete!",
    recovery_error_admin: "Recovery error: Cannot open drive (Admin rights needed?)",
    util_data_destruct: "Data destruction",
    util_overwrite_passes: "Default overwrite passes",
    util_passes: "passes",
    util_warn_drive: "Dangerous drive warning",
    util_data_recover: "Data recovery",
    util_scan_popular: "Scan popular formats only",
    util_cleanup: "Cleanup",
    util_default_mode: "Default mode",
    util_mode_quick: "Quick",
    util_mode_smart: "Smart",
    util_mode_all: "All",
    util_confirm_clean: "Confirm before cleaning",
    clean_confirm: "This will clean up system files according to the selected mode. Are you sure you want to proceed?",
    clean_finished: "Cleanup finished. Deleted: {0} items, Errors: {1} items.",
    clean_success: "Cleanup complete!",
    clean_error_occurred: "An error occurred.",
    clean_error: "Cleanup error!",
    feature_dev: "Feature is under development!",
    
    // Utilities Tab UI
    util_data_management: "Data Management",
    util_data_management_desc: "Optimize, clean up, recover, or safely destroy files on your system.",
    util_system_cleanup: "1. System Cleanup",
    util_scan_mode: "Scan mode:",
    util_scan_mode_desc: "Remove junk files, faulty registry",
    util_scan_now: "SCAN NOW",
    util_data_recovery_title: "2. Data Recovery",
    util_choose_scan_drive: "Select Drive to Scan:",
    util_drive_placeholder: "E.g.: C:, D:, E:",
    util_save_folder: "Save Folder:",
    util_choose_folder: "Choose Folder",
    util_folder_placeholder: "Not selected...",
    util_start_scan: "START SCAN",
    util_data_destruction_title: "3. Data Destruction (Secure Erase)",
    util_choose_destroy_target: "Select target to destroy:",
    util_choose_file: "Choose File",
    util_choose_drive: "Choose Drive",
    util_path_placeholder: "Path...",
    util_overwrite_passes_label: "Overwrite passes:",
    util_pass_3_rec: "3 Passes (Recommended)",
    util_pass_1_fast: "1 Pass (Fast)",
    util_pass_7_secure: "7 Passes (Extremely secure)",
    util_destroy_warning_sys: "CRITICAL WARNING: This is a system folder/drive! Destruction will corrupt Windows.",
    util_delete_anyway: "Delete Anyway",
    util_cancel: "Cancel",
    util_start_destruction: "START DESTRUCTION",

    util_mouse_lock_title: "Mouse Lock",
    util_mouse_lock_desc: "Limit mouse movement area using shortcuts.",
    util_lock_1_monitor: "1. Lock to 1 Monitor",
    util_lock_1_monitor_desc: "Prevent mouse from crossing to another monitor in multi-monitor setups.",
    util_shortcut_toggle: "Toggle shortcut:",
    util_no_shortcut: "No shortcut assigned",
    util_set_shortcut: "Set shortcut",
    util_lock_limit_area: "2. Lock in Limited Area",
    util_lock_limit_area_desc: "Confine mouse within a specified window area.",
    util_choose_window: "Choose Window",
    util_shortcut: "Shortcut:",
    util_lock_position: "3. Lock at Position",
    util_lock_position_desc: "Lock mouse strictly at a specific coordinate.",
    util_auto_get_cursor: "Automatically get current cursor coordinates when shortcut is pressed",

    // === SETTINGS ===
    settings_ui: "User Interface",
    settings_general: "General",
    settings_installer: "Installer",
    settings_uninstaller: "Uninstaller",
    settings_utilities: "Utilities",
    settings_help: "Help",
    theme_title: "Appearance",
    theme_label: "Theme:",
    lang_label: "Language:",
    font_size_label: "Font Size:",
    rounded_corners: "Rounded Corners",
    disable_animations: "Disable Animations",
    transparency_label: "Transparency:",
    always_on_top: "Always on Top",
    minimize_to_tray: "Minimize to Tray when closing",
    multithread_processing: "Silent Processing",
    multithread: "Silent installation",
    multithread_desc: "Automatically run installers and uninstallers in the background without user interaction. If a silent execution fails, it will fall back to interactive mode.",
    under_dev: "Under development",
    show_progress: "Show detailed progress",
    hide_incompatible: "Hide unsupported or incompatible applications",
    hide_unsupported: "Hide unsupported OS apps",
    show_toast: "Show toast notification when processing is complete",
    minimize_tray_install: "Minimize main window to tray when installation starts",
    minimize_tray_uninstall: "Minimize main window to tray when uninstallation starts",
    single_thread: "Single thread",
    general_system: "System & Window",
    general_process: "Processing & Notifications",
    general_ui: "Interface",
    minimize_install: "Minimize to tray during install",
    detailed_categories: "Show simple progress",
    show_complete: "Show completion dialog",
    silent_uninstall: "Silent Uninstall (if supported)",
    show_confirmation: "Show confirmation before uninstalling",
    show_progress_uninstall: "Show progress dialog",
    show_notification: "Show system notification on completion",
    minimize_on_close: "Minimize to tray instead of closing",
    remember_scan_data: "Remember scan data (Speed up)",
    update_checking: "Checking for updates...",
    update_latest: "You are using the latest version!",
    update_found: "Update available!",
    update_found_desc: "New version available: <b>{0}</b><br>Do you want to download and install it now?",
    downloading_update: "Downloading update...",
    update_error: "Cannot check for updates",
    weak_machine_warning: "Your system resources are low. Enabling effects might cause lag. Are you sure?",
    about_version: "Version 1.6",
    about_author: "Author: SpaceheroVN",
    about_github: "Source Code on GitHub",
    btn_update: "Update",

    // === HELP TEXT ===
    help_text_ui_title: "User Interface",
    help_text_ui: "<ul style='margin:0;padding-left:20px'><li><b>Theme</b>: Change the appearance of Nex Launcher to Light or Dark.</li><li><b>Language</b>: Switch between English and Vietnamese.</li><li><b>Font Size</b>: Adjust the overall size of text.</li><li><b>Transparency</b>: Adjust the transparency of the window background.</li><li><b>Rounded Corners</b>: Enable or disable modern rounded corners.</li><li><b>Disable Animations</b>: Automatically toggle animations based on hardware, or disable manually for better performance.</li></ul>",
    help_text_general_title: "General Settings",
    help_text_general: "<ul style='margin:0;padding-left:20px'><li><b>Always on Top</b>: Keeps the Nex Launcher window above other applications.</li><li><b>Minimize to Tray</b>: Minimizes the app to the system tray instead of closing.</li><li><b>Multi-threaded Processing</b>: Speeds up operations using multiple connections.</li><li><b>Show Progress</b>: Displays progress bars during tasks.</li><li><b>Show Complete Dialog</b>: Displays a notification when a task finishes.</li><li><b>Hide Unsupported</b>: Hides applications incompatible with your system.</li></ul>",
    help_text_installer_title: "Installer",
    help_text_installer: "<ul style='margin:0;padding-left:20px'><li><b>Show Confirmation</b>: Asks for confirmation before installing.</li><li><b>Update basic data</b>: Downloads the latest default software list from the server to replace your local data. This action will erase any previous custom configurations.</li></ul>",
    help_text_uninstaller_title: "Uninstaller",
    help_text_uninstaller: "<ul style='margin:0;padding-left:20px'><li><b>Show Confirmation</b>: Asks for confirmation before uninstalling.</li><li><b>Remember Scan Data</b>: Caches app icons and dates to significantly speed up future scans. Disable to force a fresh scan.</li></ul>",
    help_text_utilities_title: "Utilities",
    help_text_utilities: "<ul style='margin:0;padding-left:20px'><li><b>Data Destruction</b>: (Under development) Securely overwrite files.</li><li><b>Data Recovery</b>: (Under development) Retrieve lost files.</li><li><b>Cleanup</b>: (Under development) Free up disk space.</li></ul>",

    // === OTHERS ===
    system_label: "System",
    enter_name_id: "Please enter App Name and ID/Link",
    added_app: "Added ",
    error_saving: "Error saving",
    settings_saved: "Settings saved",
    settings_reset: "Settings reset",
    uninstaller_all: "All programs",
    uninstaller_recent: "Recently installed",
    uninstaller_large: "Large software",
    uninstaller_system: "System",
    uninstaller_external: "External",
    utilities_data: "Data",
    utilities_mouse_lock: "Mouse Lock",
    checking_data: "Checking...",
    data_up_to_date: "Data is already up to date.",
    data_update_available: "New Basic data update available...",
    updating_data: "Updating...",
    data_update_success: "Basic data updated successfully!",
    data_update_error: "An error occurred while updating.",
    data_check_error: "Error checking data from Github.",
    connection_error: "Connection error.",
    update_data_github: "Update data from Github",
    creating_restore_point: "Creating restore point...",
    skip_btn: "Skip",
    old_restore_points: "Old restore points",
    loading_text_short: "Loading..."
  },
  VN: {
    // === TRẠNG THÁI & TIẾN TRÌNH ===
    downloading: "Đang tải ",
    installing: "Đang cài đặt",
    uninstalling: "Đang gỡ ",
    processing_wait: "Đang xử lý...",
    processing: "Đang xử lý",
    completed: "Hoàn tất",
    error_status: "Lỗi",
    scanning_status: "Đang quét...",
    scanning_updates: "Đang quét bản cập nhật...",
    software_up_to_date: "Phần mềm đã được cập nhật",
    no_updates_found: "Không tìm thấy bản cập nhật nào.",
    unknown_error: "Không xác định",
    unknown: "Không rõ",
    deleting: "Đang xóa...",
    cleanup_status: "Đang dọn dẹp tàn dư hệ thống...",
    deleted: "Đã xóa",
    loading_text: "Đang quét các phần mềm được cài đặt...",
    recovering_progress: "Đang quét và khôi phục... {0}%",
    destroying_wait: "Đang tiến hành phá hủy dữ liệu. Vui lòng không tắt máy...",
    canceling: "Đang hủy...",
    clean_analyzing: "Đang phân tích và dọn dẹp...",

    // === GIAO DIỆN CHUNG & MENU ===
    window_title: "Nex-Launcher - Công cụ tiện ích tiên tiến",
    installer_btn: "Trình Cài Đặt",
    uninstaller_btn: "Trình Gỡ Cài Đặt",
    about_btn: "Giới thiệu",
    update_btn: "Kiểm tra cập nhật",
    menu_settings: "Cài đặt",
    maximize_btn: "Phóng to",
    restore_btn: "Thu nhỏ lại",
    utilities_btn: "Tiện ích",
    tab_rec: "Đề xuất",
    tab_apps: "Phần mềm",
    tab_games: "Trò chơi",
    tab_updates: "Cập nhật",
    search_placeholder: "Tìm kiếm phần mềm...",
    install_btn: "Cài đặt",
    add_btn: "Thêm",
    delete_btn: "Xóa",
    select_all: "Chọn tất cả",
    deselect_all: "Bỏ chọn tất cả",
    menu_refresh: "Làm mới danh sách",
    header_category: "Thể loại",
    header_source: "Nguồn",
    header_publisher: "Nhà phát hành",
    header_date: "Ngày cài đặt",
    header_size: "Dung lượng",
    refresh_btn: "Làm mới",
    uninstall_btn: "Gỡ cài đặt",
    next_btn: "Tiếp theo",
    close_btn: "Đóng",
    cancel_btn: "Hủy",
    save_btn: "Lưu",
    reset_btn: "Đặt lại",
    edit_btn: "Chỉnh sửa",
    confirm_btn: "Xác nhận",
    tray_show: "Hiển thị",
    tray_installer: "Trình cài đặt",
    tray_uninstaller: "Trình gỡ cài đặt",
    tray_quit: "Thoát",
    copied: "Đã Copy!",
    estimated: "Ước chừng",
    theme_light: "Sáng",
    theme_dark: "Tối",
    theme_midnight_blue: "Midnight Blue",
    theme_system: "Hệ thống",
    lang_en: "English",
    lang_vi: "Tiếng Việt",
    date_format: "DD/MM/YYYY",

    // === TRÌNH CÀI ĐẶT ===
    no_software_selected: "Chưa chọn phần mềm nào",
    confirm_install_apps: "Bạn có chắc chắn muốn cài đặt {0} phần mềm đã chọn?",
    start_installing: "Bắt đầu cài đặt ",
    apps_suffix: " phần mềm...",
    apps_suffix_short: " phần mềm",
    finish_installing: "Hoàn tất cài đặt ",
    slow_down: "Vui lòng thao tác chậm lại!",
    refreshing_list: "Đang làm mới danh sách...",
    list_refreshed: "Đã làm mới danh sách",
    no_changes: "Không có sự thay đổi mới nào.",
    enter_name_keyword: "Vui lòng nhập Tên hoặc Từ khóa để tìm",
    searching_winget: "Đang tìm trên Winget...",
    found_results: "Tìm thấy {0} kết quả. Hãy copy một ID và dán vào ô bên dưới:\n\n",
    no_results_winget: "Không tìm thấy kết quả nào",
    no_results: "Không tìm thấy phần mềm",
    no_results_desc: "Thử từ khóa khác",
    add_app_title: "Thêm phần mềm mới",
    add_app_name: "Tên phần mềm",
    add_app_name_ph: "VD: Zalo",
    add_app_category: "Thể loại",
    add_app_category_ph: "Tự nhập hoặc chọn...",
    cat_web_browsers: "Trình duyệt web",
    cat_dev_tools: "Công cụ lập trình",
    cat_media: "Đa phương tiện",
    cat_games: "Trò chơi",
    cat_utilities: "Tiện ích",
    cat_messaging: "Nhắn tin",
    cat_compression: "Nén dữ liệu",
    add_app_source: "Hình thức cài đặt",
    add_app_id_ph: "Nhập ID / Link / Từ khóa tìm kiếm",
    add_app_search_title: "Tìm kiếm trên Winget",
    add_app_silent_args_ph: "VD: /S /v/qn (Bỏ trống nếu không cần)",
    add_app_store_id_ph: "Nhập ID Store",
    add_app_cancel: "Hủy",
    add_app_add: "Thêm",
    search_winget_title_prefix: "Tìm kiếm Winget: ",
    downloading_prefix: "Đang tải (",
    edit_software_title: "Chỉnh sửa phần mềm",
    add_software_title: "Thêm phần mềm mới",

    // === TRÌNH GỠ CÀI ĐẶT ===
    confirm_uninstall: "Hiển thị hộp thoại xác nhận trước khi bắt đầu quá trình gỡ cài đặt",
    minimize_tray_uninst_label: "Thu nhỏ xuống khay khi gỡ cài đặt",
    start_uninstalling: "Bắt đầu gỡ cài đặt ",
    finish_uninstalling: "Hoàn tất gỡ cài đặt ",
    confirm_remove_apps: "Bạn có chắc muốn xóa {0} ứng dụng khỏi danh sách không?",
    successfully_removed: "Đã xóa thành công",
    error_removing: "Có lỗi khi xóa",
    no_apps: "Không tìm thấy phần mềm nào",
    status_selected: "Đã chọn {0} phần mềm",
    delete_leftovers: "Xóa Tàn Dư",
    no_registry_leftovers: "Không tìm thấy registry thừa.",
    no_file_leftovers: "Không tìm thấy file/thư mục thừa.",
    registry_entries: "Mục Registry",
    orphan_files: "File thừa",

    // === TIỆN ÍCH ===
    enter_destroy_path: "Nhập đường dẫn ổ đĩa cần phá hủy (VD: \\\\.\\PhysicalDrive1 hoặc D:)\\nLƯU Ý: Phá hủy ổ đĩa sẽ mất toàn bộ dữ liệu vĩnh viễn!",
    destroy_anyway: "Vẫn Xóa (Lần {0}/3)",
    destroy_complete: "Phá hủy dữ liệu hoàn tất!",
    destroy_error: "Lỗi phá hủy: ",
    general_error: "Đã xảy ra lỗi: ",
    recovering_title: "Nex Launcher - Đang khôi phục: {0}%",
    enter_scan_drive: "Vui lòng nhập ổ đĩa cần quét (VD: C:, D:)",
    choose_recover_folder: "Vui lòng chọn thư mục lưu kết quả khôi phục",
    starting_scan: "Đang bắt đầu quét...",
    scanning_recovering: "Đang quét và khôi phục... {0}%",
    start_recover_title: "Nex Launcher - Bắt đầu khôi phục...",
    recovery_complete: "Khôi phục dữ liệu hoàn tất!",
    recovery_error_admin: "Lỗi khôi phục: Không thể mở ổ đĩa (Cần quyền Admin?)",
    util_data_destruct: "Phá hủy dữ liệu",
    util_overwrite_passes: "Số lần ghi đè mặc định",
    util_passes: "lần",
    util_warn_drive: "Cảnh báo ổ đĩa nguy hiểm",
    util_data_recover: "Khôi phục dữ liệu",
    util_scan_popular: "Chỉ quét định dạng phổ biến",
    util_cleanup: "Dọn dẹp",
    util_default_mode: "Chế độ mặc định",
    util_mode_quick: "Nhanh",
    util_mode_smart: "Thông minh",
    util_mode_all: "Tất cả",
    util_confirm_clean: "Xác nhận trước khi dọn",
    clean_confirm: "Hành động này sẽ dọn dẹp các tập tin hệ thống theo chế độ đã chọn. Bạn có chắc chắn muốn tiếp tục?",
    clean_finished: "Đã dọn dẹp xong. Xóa: {0} mục, Lỗi: {1} mục.",
    clean_success: "Dọn dẹp hoàn tất!",
    clean_error_occurred: "Đã có lỗi xảy ra.",
    clean_error: "Lỗi khi dọn dẹp!",
    feature_dev: "Tính năng đang trong quá trình phát triển!",
    
    // Giao diện Tab Tiện ích
    util_data_management: "Quản Lý Dữ Liệu",
    util_data_management_desc: "Tối ưu hóa, dọn dẹp, khôi phục hoặc phá hủy an toàn các tệp tin trên hệ thống của bạn.",
    util_system_cleanup: "1. Dọn Dẹp Hệ Thống",
    util_scan_mode: "Chế độ quét:",
    util_scan_mode_desc: "Loại bỏ tệp tin rác, registry lỗi",
    util_scan_now: "QUÉT NGAY",
    util_data_recovery_title: "2. Khôi Phục Dữ Liệu",
    util_choose_scan_drive: "Chọn Ổ Đĩa Cần Quét:",
    util_drive_placeholder: "Ví dụ: C:, D:, E:",
    util_save_folder: "Thư Mục Lưu Tệp:",
    util_choose_folder: "Chọn Thư Mục",
    util_folder_placeholder: "Chưa chọn...",
    util_start_scan: "TIẾN HÀNH QUÉT",
    util_data_destruction_title: "3. Phá Hủy Dữ Liệu (Secure Erase)",
    util_choose_destroy_target: "Chọn đối tượng cần tiêu hủy:",
    util_choose_file: "Chọn Tệp",
    util_choose_drive: "Chọn Ổ Đĩa",
    util_path_placeholder: "Đường dẫn...",
    util_overwrite_passes_label: "Số lần ghi đè (Passes):",
    util_pass_3_rec: "3 Passes (Khuyến nghị)",
    util_pass_1_fast: "1 Pass (Nhanh)",
    util_pass_7_secure: "7 Passes (Cực kỳ an toàn)",
    util_destroy_warning_sys: "CẢNH BÁO QUAN TRỌNG: Đây là thư mục/ổ đĩa hệ thống! Phá hủy sẽ làm hỏng Windows.",
    util_delete_anyway: "Vẫn Xóa",
    util_cancel: "Hủy Bỏ",
    util_start_destruction: "TIẾN HÀNH PHÁ HỦY",

    util_mouse_lock_title: "Khóa Chuột (Mouse Lock)",
    util_mouse_lock_desc: "Giới hạn khu vực di chuyển chuột bằng các phím tắt.",
    util_lock_1_monitor: "1. Khóa ở 1 Màn Hình",
    util_lock_1_monitor_desc: "Chống trỏ chuột tràn sang màn hình khác khi dùng đa màn hình.",
    util_shortcut_toggle: "Phím tắt kích hoạt/tắt:",
    util_no_shortcut: "Chưa gán phím",
    util_set_shortcut: "Cài phím",
    util_lock_limit_area: "2. Khóa trong 1 Vùng Giới Hạn",
    util_lock_limit_area_desc: "Giới hạn chuột trong một vùng cửa sổ chỉ định.",
    util_choose_window: "Chọn Cửa Sổ",
    util_shortcut: "Phím tắt:",
    util_lock_position: "3. Khóa Tại Vị Trí",
    util_lock_position_desc: "Khóa cứng chuột tại một tọa độ nhất định.",
    util_auto_get_cursor: "Tự động lấy tọa độ con trỏ hiện tại khi bấm phím tắt",

    // === CÀI ĐẶT (SETTINGS) ===
    settings_ui: "Giao diện",
    settings_general: "Chung",
    settings_installer: "Trình Cài Đặt",
    settings_uninstaller: "Trình Gỡ Cài Đặt",
    settings_utilities: "Tiện Ích",
    settings_help: "Trợ giúp",
    theme_title: "Chủ đề",
    theme_label: "Chủ đề:",
    lang_label: "Ngôn ngữ:",
    font_size_label: "Cỡ chữ:",
    rounded_corners: "Bo tròn góc",
    disable_animations: "Tắt hiệu ứng",
    transparency_label: "Độ trong suốt:",
    always_on_top: "Luôn ở trên cùng",
    minimize_to_tray: "Thu nhỏ xuống khay khi đóng",
    multithread_processing: "Xử lý ngầm",
    multithread: "Bật xử lý ngầm",
    multithread_desc: "Tự động chạy các lệnh cài đặt và gỡ cài đặt dưới nền mà không hiển thị cửa sổ. Nếu chạy ngầm thất bại, hệ thống sẽ tự động chuyển sang chế độ hiển thị.",
    under_dev: "Đang trong phát triển",
    show_progress: "Hiển thị tiến trình chi tiết",
    hide_incompatible: "Ẩn các ứng dụng không được hỗ trợ hoặc không tương thích",
    hide_unsupported: "Ẩn ứng dụng không hỗ trợ",
    show_toast: "Hiển thị thông báo (toast) ở góc màn hình khi quá trình xử lý hoàn tất",
    minimize_tray_install: "Thu nhỏ giao diện chính xuống khay hệ thống khi quá trình cài đặt bắt đầu",
    minimize_tray_uninstall: "Thu nhỏ giao diện chính xuống khay hệ thống khi quá trình gỡ cài đặt bắt đầu",
    single_thread: "Đơn luồng",
    general_system: "Hệ thống & Cửa sổ",
    general_process: "Tiến trình & Thông báo",
    general_ui: "Giao diện",
    minimize_install: "Thu nhỏ xuống khay khi cài đặt",
    detailed_categories: "Hiển thị tiến trình đơn giản",
    show_complete: "Hiển thị thông báo hoàn tất",
    silent_uninstall: "Gỡ cài đặt ngầm (nếu hỗ trợ)",
    show_confirmation: "Hiển thị xác nhận trước khi gỡ",
    show_progress_uninstall: "Hiển thị tiến trình",
    show_notification: "Hiển thị thông báo khi hoàn tất",
    minimize_on_close: "Thu nhỏ xuống khay thay vì đóng",
    remember_scan_data: "Ghi nhớ dữ liệu khi quét",
    update_checking: "Đang kiểm tra cập nhật...",
    update_latest: "Bạn đang dùng phiên bản mới nhất!",
    update_found: "Có phiên bản mới!",
    update_found_desc: "Có phiên bản mới: <b>{0}</b><br>Bạn có muốn tải xuống và cài đặt ngay không?",
    downloading_update: "Tải xuống bản cập nhật...",
    update_error: "Không thể kiểm tra cập nhật",
    weak_machine_warning: "Máy bạn có cấu hình khá yếu hoặc đang thiếu tài nguyên trống. Việc BẬT hiệu ứng có thể gây giật lag hoặc phản hồi chậm. Bạn có chắc chắn muốn bật hiệu ứng không?",
    about_version: "Phiên bản 1.6",
    about_author: "Tác giả: SpaceheroVN",
    about_github: "Mã nguồn trên GitHub",
    btn_update: "Cập nhật",

    // === TRỢ GIÚP (HELP TEXT) ===
    help_text_ui_title: "Giao diện",
    help_text_ui: "<ul style='margin:0;padding-left:20px'><li><b>Giao diện</b>: Chuyển đổi giữa chế độ Sáng và Tối.</li><li><b>Ngôn ngữ</b>: Chuyển đổi giữa Tiếng Anh và Tiếng Việt.</li><li><b>Cỡ chữ</b>: Điều chỉnh kích thước văn bản hiển thị.</li><li><b>Độ trong suốt</b>: Điều chỉnh độ trong suốt của nền cửa sổ.</li><li><b>Bo tròn góc</b>: Bật/tắt thiết kế bo tròn hiện đại.</li><li><b>Tắt hiệu ứng</b>: Tự động tắt/bật hiệu ứng thông minh theo cấu hình máy, hoặc tắt thủ công để tối ưu hiệu suất.</li></ul>",
    help_text_general_title: "Cài đặt chung",
    help_text_general: "<ul style='margin:0;padding-left:20px'><li><b>Luôn ở trên cùng</b>: Giữ cửa sổ Nex Launcher luôn nổi trên các ứng dụng khác.</li><li><b>Thu nhỏ xuống khay</b>: Khi đóng, ứng dụng sẽ thu nhỏ xuống góc màn hình thay vì tắt hẳn.</li><li><b>Xử lý đa luồng</b>: Tăng tốc quá trình bằng cách sử dụng nhiều kết nối cùng lúc.</li><li><b>Hiển thị tiến trình</b>: Hiển thị thanh tiến trình khi đang chạy.</li><li><b>Hiển thị thông báo hoàn tất</b>: Thông báo khi quá trình xử lý xong.</li><li><b>Ẩn ứng dụng không hỗ trợ</b>: Ẩn các ứng dụng không tương thích với hệ thống hiện tại.</li></ul>",
    help_text_installer_title: "Trình Cài Đặt",
    help_text_installer: "<ul style='margin:0;padding-left:20px'><li><b>Hiển thị xác nhận cài đặt</b>: Hỏi ý kiến trước khi cài đặt.</li><li><b>Cập nhật dữ liệu cơ bản</b>: Tải về danh sách phần mềm mặc định mới nhất từ máy chủ để thay thế dữ liệu hiện tại trên máy của bạn. Hành động này sẽ xóa mọi cấu hình thay đổi trước đó.</li></ul>",
    help_text_uninstaller_title: "Trình Gỡ Cài Đặt",
    help_text_uninstaller: "<ul style='margin:0;padding-left:20px'><li><b>Hiện hộp thoại xác nhận</b>: Hỏi ý kiến trước khi gỡ.</li><li><b>Ghi nhớ dữ liệu khi quét</b>: Lưu lại dữ liệu biểu tượng và ngày cài đặt để tăng tốc độ tải trong những lần mở sau. Nếu tắt, ứng dụng sẽ quét lại từ đầu.</li></ul>",
    help_text_utilities_title: "Tiện Ích",
    help_text_utilities: "<ul style='margin:0;padding-left:20px'><li><b>Phá hủy dữ liệu</b>: (Đang phát triển) Ghi đè tệp tin an toàn.</li><li><b>Khôi phục dữ liệu</b>: (Đang phát triển) Lấy lại các tệp tin đã mất.</li><li><b>Dọn dẹp</b>: (Đang phát triển) Giải phóng dung lượng ổ đĩa.</li></ul>",

    // === KHÁC ===
    system_label: "Hệ thống",
    enter_name_id: "Vui lòng nhập Tên phần mềm và ID/Link",
    added_app: "Đã thêm ",
    error_saving: "Có lỗi khi lưu",
    settings_saved: "Đã lưu cài đặt",
    settings_reset: "Đã đặt lại cài đặt",
    uninstaller_all: "Mọi chương trình",
    uninstaller_recent: "Cài đặt gần đây",
    uninstaller_large: "Phần mềm lớn",
    uninstaller_system: "Hệ thống",
    uninstaller_external: "Bên ngoài",
    utilities_data: "Dữ liệu",
    utilities_mouse_lock: "Khóa chuột",
    checking_data: "Đang kiểm tra...",
    data_up_to_date: "Dữ liệu hiện tại đã là mới nhất.",
    data_update_available: "Có bản cập nhật dữ liệu Basic mới...",
    updating_data: "Đang cập nhật...",
    data_update_success: "Cập nhật dữ liệu Basic thành công!",
    data_update_error: "Có lỗi xảy ra khi cập nhật.",
    data_check_error: "Lỗi kiểm tra dữ liệu từ Github.",
    connection_error: "Lỗi kết nối.",
    update_data_github: "Cập nhật dữ liệu từ Github",
    creating_restore_point: "Đang tiến hành tạo điểm khôi phục...",
    skip_btn: "Bỏ qua",
    old_restore_points: "Các điểm khôi phục cũ",
    loading_text_short: "Đang tải..."
  }
};
