var Languages = {
  EN: {
    downloading: "Downloading",
    installing: "Installing",
    uninstalling: "Uninstalling",
    processing_wait: "Please wait for the process to complete",
    no_software_selected: "Please select software",
    scanning_status: "Scanning...",
    scanning_updates: "Scanning for updates...",
    unknown_error: "Unknown error",
    theme_light: "Light",
    theme_dark: "Dark",
    theme_system: "System",
    lang_en: "English",
    lang_vi: "Tiếng Việt",
    multithread_processing: "Multithreaded Processing",
    multithread_desc: "Automatic multithreaded processing. Falls back to single thread for specific files (.msi) on retry (max 3 times).",
    under_dev: "Under development",
    show_progress: "Show detailed progress dialog during installation or uninstallation",
    hide_incompatible: "Automatically hide applications incompatible with the current OS",
    show_toast: "Show toast notification when processing is complete",
    minimize_tray_install: "Minimize main window to tray when installation starts",
    confirm_uninstall: "Show confirmation dialog before uninstalling",
    minimize_tray_uninstall: "Minimize main window to tray when uninstallation starts",
    minimize_tray_uninst_label: "Minimize to tray on uninstall",
    single_thread: "Single thread",
    processing: "Processing",
    completed: "Completed",
    error_status: "Error",
    copied: "Copied!",
    enter_destroy_path: "Enter the drive path to destroy (e.g. \\\\.\\PhysicalDrive1 or D:)\\nWARNING: Destroying the drive will permanently erase all data!",
    destroy_anyway: "Still Destroy ({0}/3)",
    destroying_wait: "Destroying data. Please do not turn off the computer...",
    destroy_complete: "Data destruction complete!",
    destroy_error: "Destruction error: ",
    general_error: "An error occurred: ",
    recovering_progress: "Scanning and recovering... {0}%",
    recovering_title: "Nex Launcher - Recovering: {0}%",
    enter_scan_drive: "Please enter the drive to scan (e.g. C:, D:)",
    choose_recover_folder: "Please select a folder to save recovered files",
    starting_scan: "Starting scan...",
    start_recover_title: "Nex Launcher - Starting recovery...",
    recovery_complete: "Data recovery complete!",
    recovery_error_admin: "Recovery error: Cannot open drive (Need Admin rights?)",
    deleting: "Deleting...",
    delete_leftovers: "Delete Leftovers",
    no_registry_leftovers: "No registry leftovers found.",
    no_file_leftovers: "No file/folder leftovers found.",
    registry_entries: "Registry entries",
    orphan_files: "Orphan files",
    window_title: "Nex-Launcher - Advanced Utility Tool",
    installer_btn: "Installer", uninstaller_btn: "Uninstaller", about_btn: "About",
    update_btn: "Check for Updates", menu_settings: "Settings",
    tab_all: "All", tab_apps: "Apps", tab_games: "Games", tab_updates: "Updates",
    search_placeholder: "Search software...", install_btn: "Install", add_btn: "Add", delete_btn: "Delete",
    header_name: "Name", header_category: "Category", header_source: "Source",
    header_publisher: "Publisher", header_date: "Install Date", header_size: "Size",
    no_results: "No software found", no_results_desc: "Try a different search term",
    refresh_btn: "Refresh", uninstall_btn: "Uninstall",
    loading_text: "Scanning installed applications...", status_selected: "Selected {0} app(s)",
    no_apps: "No applications found", about_version: "Version 1.6", about_author: "Author: SpaceheroVN",
    about_github: "Source Code on GitHub",
    settings_ui: "User Interface", settings_general: "General", settings_installer: "Installer",
    settings_uninstaller: "Uninstaller", settings_utilities: "Utilities", settings_help: "Help",
    util_data_destruct: "Data Destruction", util_overwrite_passes: "Default overwrite passes",
    util_passes: "passes", util_warn_drive: "Warn on dangerous drives",
    util_data_recover: "Data Recovery", util_scan_popular: "Scan popular formats only",
    util_cleanup: "System Cleanup", util_default_mode: "Default mode",
    util_mode_quick: "Quick", util_mode_smart: "Smart", util_mode_all: "All",
    util_confirm_clean: "Confirm before cleaning",
    theme_title: "Appearance", theme_label: "Theme:", lang_label: "Language:",
    font_size_label: "Font Size:", rounded_corners: "Rounded Corners",
    disable_animations: "Disable Animations", transparency_label: "Transparency:",
    always_on_top: "Always on Top", minimize_to_tray: "Minimize to Tray when closing",
    multithread: "Multi-thread installation", auto_select: "Auto-select after adding",
    minimize_install: "Minimize to tray during install", detailed_categories: "Use detailed categories",
    show_progress: "Show progress dialog", hide_unsupported: "Hide unsupported OS apps",
    show_complete: "Show completion dialog",
    silent_uninstall: "Silent Uninstall (if supported)", show_confirmation: "Show confirmation before uninstalling",
    show_progress_uninstall: "Show progress dialog", show_notification: "Show system notification on completion",
    minimize_on_close: "Minimize to tray instead of closing",
    reset_btn: "Reset", cancel_btn: "Cancel", save_btn: "Save",
    update_checking: "Checking for updates...", update_latest: "You are on the latest version!",
    update_found: "New version available!", update_error: "Failed to check for updates",
    help_text_ui_title: "User Interface",
    help_text_ui: "- <b>Theme</b>: Change the appearance of Nex Launcher to Light or Dark.<br>- <b>Language</b>: Switch between English and Vietnamese.<br>- <b>Font Size</b>: Adjust the overall size of text.<br>- <b>Rounded Corners</b>: Enable or disable modern rounded corners.<br>- <b>Disable Animations</b>: Automatically toggle animations based on hardware, or disable manually for better performance.",
    help_text_general_title: "General Settings",
    help_text_general: "- <b>Always on Top</b>: Keeps the Nex Launcher window above other applications.<br>- <b>Minimize to Tray</b>: Minimizes the app to the system tray instead of closing.",
    help_text_installer_title: "Installer",
    help_text_installer: "- <b>Multi-threaded Download</b>: Speeds up downloads using multiple connections.<br>- <b>Auto-select All</b>: Automatically checks all software when opened.<br>- <b>Hide Unsupported</b>: Hides applications incompatible with your system.<br>- <b>Show Complete Dialog</b>: Displays a notification when installation finishes.",
    help_text_uninstaller_title: "Uninstaller",
    help_text_uninstaller: "- <b>Silent Uninstall</b>: Uninstalls software automatically without showing its UI.<br>- <b>Show Confirmation</b>: Asks for confirmation before uninstalling.<br>- <b>Minimize on Close</b>: Minimizes the Uninstaller after completion.",
    help_text_utilities_title: "Utilities",
    help_text_utilities: "- <b>Data Destruction</b>: (Under development) Securely overwrite files.<br>- <b>Data Recovery</b>: (Under development) Retrieve lost files.<br>- <b>Cleanup</b>: (Under development) Free up disk space.",
    system_label: "System",
    date_format: "MM/DD/YYYY",
    unknown: "Unknown",
    installing: "Installing", downloading: "Downloading ", uninstalling: "Uninstalling ",
    processing_wait: "Processing, please wait...", no_software_selected: "No software selected",
    start_installing: "Starting installation for ", apps_suffix: " apps...", apps_suffix_short: " apps",
    finish_installing: "Finished installing ", slow_down: "Please slow down!",
    refreshing_list: "Refreshing list...", list_refreshed: "List refreshed", no_changes: "No new changes detected.",
    start_uninstalling: "Starting uninstallation for ", finish_uninstalling: "Finished uninstalling ",
    enter_name_id: "Please enter App Name and ID/Link", added_app: "Added ", error_saving: "Error saving",
    enter_name_keyword: "Please enter Name or Keyword to search", searching_winget: "Searching on Winget...",
    found_results: "Found {0} results. Please copy an ID and paste it below:\n\n", no_results_winget: "No results found",
    confirm_remove_apps: "Remove {0} apps?", successfully_removed: "Successfully removed", error_removing: "Error removing",
    edit_btn: "Edit", estimated: "Estimated", settings_saved: "Settings saved", settings_reset: "Settings reset",
    add_app_title: "Add New App", add_app_name: "App Name", add_app_name_ph: "Ex: Zalo",
    add_app_category: "Category", add_app_category_ph: "Type or select...", add_app_source: "Source type",
    add_app_id_ph: "Enter ID / Link / Search keyword", add_app_search_title: "Search on Winget",
    add_app_silent_args_ph: "Ex: /S /v/qn (Leave blank if not needed)", add_app_store_id_ph: "Enter Store ID",
    add_app_cancel: "Cancel", add_app_add: "Add", theme_light: "Light", theme_dark: "Dark",
    tray_show: "Show", tray_installer: "Installer", tray_uninstaller: "Uninstaller", tray_quit: "Quit",
    utilities_btn: "Utilities", search_winget_title_prefix: "Search Winget: ",
    downloading_prefix: "Downloading (", feature_dev: "Feature is under development!",
    confirm_btn: "Confirm", edit_software_title: "Edit Software", add_software_title: "Add new software",
    btn_update: "Update", weak_machine_warning: "Your system resources are low. Enabling effects might cause lag. Are you sure?",
    close_btn: "Close", canceling: "Canceling...", clean_confirm: "This action will clean system files according to the selected mode. Are you sure you want to continue?",
    clean_analyzing: "Analyzing and cleaning...", clean_finished: "Cleanup finished. Deleted: {0} items, Errors: {1} items.",
    clean_success: "Cleanup finished!", clean_error_occurred: "An error occurred.", clean_error: "Error during cleanup!"
  },
  VN: {
    downloading: "Đang tải",
    installing: "Đang cài đặt",
    uninstalling: "Đang gỡ cài đặt",
    processing_wait: "Vui lòng chờ tiến trình hoàn tất",
    no_software_selected: "Vui lòng chọn phần mềm",
    scanning_status: "Đang quét...",
    scanning_updates: "Đang quét bản cập nhật...",
    unknown_error: "Không xác định",
    theme_light: "Sáng",
    theme_dark: "Tối",
    theme_system: "Hệ thống",
    lang_en: "English",
    lang_vi: "Tiếng Việt",
    multithread_processing: "Đa luồng xử lý",
    multithread_desc: "Đa luồng và tự xử lý cả cài đặt và gỡ cài đặt. Nếu gặp file đơn luồng (như .msi), tự chuyển sang đơn luồng ở lần thử lại tiếp theo (tối đa 3 lần).",
    under_dev: "Đang trong phát triển",
    show_progress: "Hiển thị hộp thoại tiến trình chi tiết khi cài đặt hoặc gỡ cài đặt",
    hide_incompatible: "Tự động ẩn các ứng dụng không tương thích với hệ điều hành hiện tại",
    show_toast: "Hiển thị thông báo (toast) ở góc màn hình khi quá trình xử lý hoàn tất",
    minimize_tray_install: "Thu nhỏ giao diện chính xuống khay hệ thống khi quá trình cài đặt bắt đầu",
    confirm_uninstall: "Hiển thị hộp thoại xác nhận trước khi bắt đầu quá trình gỡ cài đặt",
    minimize_tray_uninstall: "Thu nhỏ giao diện chính xuống khay hệ thống khi quá trình gỡ cài đặt bắt đầu",
    minimize_tray_uninst_label: "Thu nhỏ xuống khay khi gỡ cài đặt",
    single_thread: "Đơn luồng",
    processing: "Đang xử lý",
    completed: "Hoàn tất",
    error_status: "Lỗi",
    copied: "Đã Copy!",
    enter_destroy_path: "Nhập đường dẫn ổ đĩa cần phá hủy (VD: \\\\.\\PhysicalDrive1 hoặc D:)\\nLƯU Ý: Phá hủy ổ đĩa sẽ mất toàn bộ dữ liệu vĩnh viễn!",
    destroy_anyway: "Vẫn Xóa (Lần {0}/3)",
    destroying_wait: "Đang tiến hành phá hủy dữ liệu. Vui lòng không tắt máy...",
    destroy_complete: "Phá hủy dữ liệu hoàn tất!",
    destroy_error: "Lỗi phá hủy: ",
    general_error: "Đã xảy ra lỗi: ",
    recovering_progress: "Đang quét và khôi phục... {0}%",
    recovering_title: "Nex Launcher - Đang khôi phục: {0}%",
    enter_scan_drive: "Vui lòng nhập ổ đĩa cần quét (VD: C:, D:)",
    choose_recover_folder: "Vui lòng chọn thư mục lưu kết quả khôi phục",
    starting_scan: "Đang bắt đầu quét...",
    start_recover_title: "Nex Launcher - Bắt đầu khôi phục...",
    recovery_complete: "Khôi phục dữ liệu hoàn tất!",
    recovery_error_admin: "Lỗi khôi phục: Không thể mở ổ đĩa (Cần quyền Admin?)",
    deleting: "Đang xóa...",
    delete_leftovers: "Xóa Tàn Dư",
    no_registry_leftovers: "Không tìm thấy registry thừa.",
    no_file_leftovers: "Không tìm thấy file/thư mục thừa.",
    registry_entries: "Mục Registry",
    orphan_files: "File thừa",
    window_title: "Nex-Launcher - Công cụ tiện ích tiên tiến",
    installer_btn: "Trình Cài Đặt", uninstaller_btn: "Trình Gỡ Cài Đặt", about_btn: "Giới thiệu",
    update_btn: "Kiểm tra cập nhật", menu_settings: "Cài đặt",
    tab_all: "Tất cả", tab_apps: "Phần mềm", tab_games: "Trò chơi", tab_updates: "Cập nhật",
    search_placeholder: "Tìm kiếm phần mềm...", install_btn: "Cài đặt", add_btn: "Thêm", delete_btn: "Xóa",
    header_name: "Tên phần mềm", header_category: "Thể loại", header_source: "Nguồn",
    header_publisher: "Nhà phát hành", header_date: "Ngày cài đặt", header_size: "Dung lượng",
    no_results: "Không tìm thấy phần mềm", no_results_desc: "Thử từ khóa khác",
    refresh_btn: "Làm mới", uninstall_btn: "Gỡ cài đặt",
    loading_text: "Đang quét các phần mềm được cài đặt...", status_selected: "Đã chọn {0} phần mềm",
    no_apps: "Không tìm thấy phần mềm nào", about_version: "Phiên bản 1.6", about_author: "Tác giả: SpaceheroVN",
    about_github: "Mã nguồn trên GitHub",
    settings_ui: "Giao diện", settings_general: "Chung", settings_installer: "Trình Cài Đặt",
    settings_uninstaller: "Trình Gỡ Cài Đặt", settings_utilities: "Tiện Ích", settings_help: "Trợ giúp",
    util_data_destruct: "Phá hủy dữ liệu", util_overwrite_passes: "Số lần ghi đè mặc định",
    util_passes: "lần", util_warn_drive: "Cảnh báo ổ đĩa nguy hiểm",
    util_data_recover: "Khôi phục dữ liệu", util_scan_popular: "Chỉ quét định dạng phổ biến",
    util_cleanup: "Dọn dẹp", util_default_mode: "Chế độ mặc định",
    util_mode_quick: "Nhanh", util_mode_smart: "Thông minh", util_mode_all: "Tất cả",
    util_confirm_clean: "Xác nhận trước khi dọn",
    theme_title: "Chủ đề", theme_label: "Chủ đề:", lang_label: "Ngôn ngữ:",
    font_size_label: "Cỡ chữ:", rounded_corners: "Bo tròn góc",
    disable_animations: "Tắt hiệu ứng", transparency_label: "Độ trong suốt:",
    always_on_top: "Luôn ở trên cùng", minimize_to_tray: "Thu nhỏ xuống khay khi đóng",
    multithread: "Bật cài đặt đa luồng", auto_select: "Tự động chọn sau khi thêm",
    minimize_install: "Thu nhỏ xuống khay khi cài đặt", detailed_categories: "Sử dụng danh mục chi tiết",
    show_progress: "Hiển thị tiến trình", hide_unsupported: "Ẩn ứng dụng không hỗ trợ",
    show_complete: "Hiển thị thông báo hoàn tất",
    silent_uninstall: "Gỡ cài đặt ngầm (nếu hỗ trợ)", show_confirmation: "Hiển thị xác nhận trước khi gỡ",
    show_progress_uninstall: "Hiển thị tiến trình", show_notification: "Hiển thị thông báo khi hoàn tất",
    minimize_on_close: "Thu nhỏ xuống khay thay vì đóng",
    reset_btn: "Đặt lại", cancel_btn: "Hủy", save_btn: "Lưu",
    update_checking: "Đang kiểm tra cập nhật...", update_latest: "Bạn đang dùng phiên bản mới nhất!",
    update_found: "Có phiên bản mới!", update_error: "Không thể kiểm tra cập nhật",
    help_text_ui_title: "Giao diện",
    help_text_ui: "- <b>Giao diện</b>: Chuyển đổi giữa chế độ Sáng và Tối.<br>- <b>Ngôn ngữ</b>: Chuyển đổi giữa Tiếng Anh và Tiếng Việt.<br>- <b>Cỡ chữ</b>: Điều chỉnh kích thước văn bản hiển thị.<br>- <b>Bo tròn góc</b>: Bật/tắt thiết kế bo tròn hiện đại.<br>- <b>Tắt hiệu ứng</b>: Tự động tắt/bật hiệu ứng thông minh theo cấu hình máy, hoặc tắt thủ công để tối ưu hiệu suất.",
    help_text_general_title: "Cài đặt chung",
    help_text_general: "- <b>Luôn ở trên cùng</b>: Giữ cửa sổ Nex Launcher luôn nổi trên các ứng dụng khác.<br>- <b>Thu nhỏ xuống khay</b>: Khi đóng, ứng dụng sẽ thu nhỏ xuống góc màn hình thay vì tắt hẳn.",
    help_text_installer_title: "Trình Cài Đặt",
    help_text_installer: "- <b>Tải đa luồng</b>: Tăng tốc độ tải bằng cách sử dụng nhiều kết nối cùng lúc.<br>- <b>Tự động chọn tất cả</b>: Tự động đánh dấu tất cả phần mềm khi mở.<br>- <b>Ẩn ứng dụng không hỗ trợ</b>: Ẩn các ứng dụng không tương thích với hệ thống hiện tại.<br>- <b>Hiển thị hộp thoại khi hoàn tất</b>: Thông báo khi quá trình cài đặt xong.",
    help_text_uninstaller_title: "Trình Gỡ Cài Đặt",
    help_text_uninstaller: "- <b>Gỡ cài đặt ngầm</b>: Gỡ phần mềm tự động không hiện giao diện.<br>- <b>Hiện hộp thoại xác nhận</b>: Hỏi ý kiến trước khi gỡ.<br>- <b>Thu nhỏ khi đóng</b>: Thu nhỏ Trình gỡ cài đặt sau khi gỡ xong.",
    help_text_utilities_title: "Tiện Ích",
    help_text_utilities: "- <b>Phá hủy dữ liệu</b>: (Đang phát triển) Ghi đè tệp tin an toàn.<br>- <b>Khôi phục dữ liệu</b>: (Đang phát triển) Lấy lại các tệp tin đã mất.<br>- <b>Dọn dẹp</b>: (Đang phát triển) Giải phóng dung lượng ổ đĩa.",
    system_label: "Hệ thống",
    date_format: "DD/MM/YYYY",
    unknown: "Không rõ",
    installing: "Đang cài đặt", downloading: "Đang tải ", uninstalling: "Đang gỡ ",
    processing_wait: "Đang xử lý...", no_software_selected: "Chưa chọn phần mềm nào",
    start_installing: "Bắt đầu cài đặt ", apps_suffix: " phần mềm...", apps_suffix_short: " phần mềm",
    finish_installing: "Hoàn tất cài đặt ", slow_down: "Vui lòng thao tác chậm lại!",
    refreshing_list: "Đang làm mới danh sách...", list_refreshed: "Đã làm mới danh sách", no_changes: "Không có sự thay đổi mới nào.",
    start_uninstalling: "Bắt đầu gỡ cài đặt ", finish_uninstalling: "Hoàn tất gỡ cài đặt ",
    enter_name_id: "Vui lòng nhập Tên phần mềm và ID/Link", added_app: "Đã thêm ", error_saving: "Có lỗi khi lưu",
    enter_name_keyword: "Vui lòng nhập Tên hoặc Từ khóa để tìm", searching_winget: "Đang tìm trên Winget...",
    found_results: "Tìm thấy {0} kết quả. Hãy copy một ID và dán vào ô bên dưới:\n\n", no_results_winget: "Không tìm thấy kết quả nào",
    confirm_remove_apps: "Bạn có chắc muốn xóa {0} ứng dụng khỏi danh sách không?", successfully_removed: "Đã xóa thành công", error_removing: "Có lỗi khi xóa",
    edit_btn: "Chỉnh sửa", estimated: "Ước chừng", settings_saved: "Đã lưu cài đặt", settings_reset: "Đã đặt lại cài đặt",
    add_app_title: "Thêm phần mềm mới", add_app_name: "Tên phần mềm", add_app_name_ph: "VD: Zalo",
    add_app_category: "Thể loại", add_app_category_ph: "Tự nhập hoặc chọn...", add_app_source: "Hình thức cài đặt",
    add_app_id_ph: "Nhập ID / Link / Từ khóa tìm kiếm", add_app_search_title: "Tìm kiếm trên Winget",
    add_app_silent_args_ph: "VD: /S /v/qn (Bỏ trống nếu không cần)", add_app_store_id_ph: "Nhập ID Store",
    add_app_cancel: "Hủy", add_app_add: "Thêm", theme_light: "Sáng", theme_dark: "Tối",
    tray_show: "Hiển thị", tray_installer: "Trình cài đặt", tray_uninstaller: "Trình gỡ cài đặt", tray_quit: "Thoát",
    utilities_btn: "Tiện ích", search_winget_title_prefix: "Tìm kiếm Winget: ",
    downloading_prefix: "Đang tải (", feature_dev: "Tính năng đang trong quá trình phát triển!",
    confirm_btn: "Xác nhận", edit_software_title: "Chỉnh sửa phần mềm", add_software_title: "Thêm phần mềm mới",
    btn_update: "Cập nhật", weak_machine_warning: "Máy bạn có cấu hình khá yếu hoặc đang thiếu tài nguyên trống. Việc BẬT hiệu ứng có thể gây giật lag hoặc phản hồi chậm. Bạn có chắc chắn muốn bật hiệu ứng không?",
    close_btn: "Đóng", canceling: "Đang hủy...", clean_confirm: "Hành động này sẽ dọn dẹp các tập tin hệ thống theo chế độ đã chọn. Bạn có chắc chắn muốn tiếp tục?",
    clean_analyzing: "Đang phân tích và dọn dẹp...", clean_finished: "Đã dọn dẹp xong. Xóa: {0} mục, Lỗi: {1} mục.",
    clean_success: "Dọn dẹp hoàn tất!", clean_error_occurred: "Đã có lỗi xảy ra.", clean_error: "Lỗi khi dọn dẹp!"
  }
};
